version: '3.9'

services:
  python:
    image: python:latest
    working_dir: /root/app
    ports:
      - "8008:8080"
    volumes:
      - ./:/root/app
    links:
      - "mysql:mysql"
    command: bash run.sh
  
  nginx:
    image: nginx:latest
    ports:
      - "8005:8005"
    volumes:
      - ./nginx:/etc/nginx

  mysql:
    image: mysql:latest
    ports:
      - "8006:3306"
    env_file:
      - ./secrets/env-mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8007:80"
    links:
      - "mysql:db"